### ISSUE TITLE
Will this work with prisma 5.0.0?

### ISSUE THREAD

**Issue by codepunkt** [Quramy/prisma-fabbrica#165]
Awesome library! Will this work with prisma `5.0.0`?

**Comment by Quramy** [comment]
@codepunkt 

For now, codes generated by prisma-fabbrica can occur TypeScript compilation errors because this [Prisma client's change](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#removal-of-array-shortcuts).

And I'm planning fix this issue.

**Comment by codepunkt** [comment]
Awesome @Quramy, that would be great!

**Comment by Quramy** [comment]
I published `@quramy/prisma-fabbrica` v2.0.0, it's compatible for `@prisma/client` v5.
