### ISSUE TITLE
Typecheck failing when noTranspile is true when updating to v2.2.0

### ISSUE THREAD

**Issue by splicebison** [Quramy/prisma-fabbrica#349]
**Describe the bug**
When using the option `noTranspile = true`, type checking is failing in multiple lines with the type error TS2532: Object is possibly 'undefined'. 

This is **only** applicable to using the noTranspile option. When using the default setup in combination with `skipLibCheck: true` compiler option in tsconfig, type check passes.

Example:

```
src/generated/prisma-fabbrica/index.ts:392:42 - error TS2532: Object is possibly 'undefined'.
392             ...traitKeys.map(traitKey => traitsDefs[traitKey].onAfterCreate),
```

**To Reproduce**

1. Add noTranspile option to config:
```
generator fabbrica {
  provider    = "prisma-fabbrica"
  output      = "../src/generated/prisma-fabbrica"
  noTranspile = true
}
```
2. Run codegen
3. Run typecheck (or open the generated file in your IDE) ex: `yarn tsc --project ./tsconfig.json --noEmit`

**Expected behavior**
Typechecks to pass

**Environment (please complete the following information):**

- Database kind PostgreSQL
- Node.js version 20.9.0
- `@prisma/client` version 5.16.1
- TypeScript version 5.5.3

**Comment by Quramy** [comment]
Would you paste your tsconfig.json ?

**Comment by splicebison** [comment]
The actual tsconfig is extending some config however this is the combined ruleset and config for this specific package.
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "useUnknownInCatchVariables": true,
    "noImplicitOverride": true,
    "noUncheckedIndexedAccess": true,
    "allowUnreachableCode": false,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noEmit": true,
    "esModuleInterop": true,
    "incremental": true,
    "newLine": "lf",
    "strict": true,
    "target": "ESNext",
    "lib": ["ESNext"],
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "noEmit": false,
    "baseUrl": "./src",
    "outDir": "./dist",
    "verbatimModuleSyntax": false,
    "types": ["vitest/globals", "vitest-environment-vprisma"]
  },
  "exclude": ["**/node_modules", "**/.*/*", "dist"],
  "include": [
    ".eslintrc.*s",
    "**/*.ts",
    "**/*.mts",
    "**/*.js",
    "**/*.cjs",
    "**/*.mjs",
    "**/*.json"
  ]
}
```

*Note that excluding the generated folder using `exclude` has no effect in this case as other TS files within the src are importing directly from the generated file's index.ts. Hence the type check failure.

**Comment by Quramy** [comment]
@splicebison I fixed this issue and released as v2.2.1

**Comment by splicebison** [comment]
Excellent and quick turnaround. I'll pull down the latest. Thanks
